Change Error code for undefined in relative comparison - fixes #220
dudykr/stc pull request #228
Opened 2022-11-06 14:02 UTC by Camc314

**Description:**

fixes #220 

**BREAKING CHANGE:**

**Related issue (if exists):**

2022-11-06 16:49 UTC, littledivy commented on crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs
> +                if let stc_ts_types::Type::Keyword(KeywordType {
nit
```suggestion
                if let Type::Keyword(KeywordType {
```

2022-11-06 16:49 UTC, littledivy commented on crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs
> +                if let stc_ts_types::Type::Keyword(KeywordType {
```suggestion
                if let Type::Keyword(KeywordType {
```

2022-11-06 16:52 UTC, camc314 commented on crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs
> +                if let stc_ts_types::Type::Keyword(KeywordType {
oh yeah, thanks :+1:

2022-11-07 02:31 UTC, kdy1 requested changes

2022-11-07 02:31 UTC, kdy1 commented on crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs
> +                    return Err(Error::UndefinedInRelativeComparison { span: rt.span() });
I think we should recover from this.

2022-11-07 02:31 UTC, kdy1 commented on crates/stc_ts_file_analyzer/src/analyzer/expr/bin.rs
> +                    return Err(Error::UndefinedInRelativeComparison { span: rt.span() });
Please store the error in `self.storage`

2022-11-07 09:24 UTC, kdy1 approved these changes
Thank you!

2022-11-07 09:28 UTC, kdy1 approved these changes

2022-11-07 09:46 UTC, merged