feat(ts/analzer): intersection reduction
dudykr/stc pull request #422
Opened 2022-12-20 03:56 UTC by sunrabbit123

**Description:**

Resolve IntersectionReduction

**BREAKING CHANGE:**

if rhs.isAny, check `to` is never
if `to` is Never and rhs.isAny, fail!

and

LValue is Intersection

1. represent `intersection_normalize`
2. Fix if property is `readonly keyword | keyword`, throw readonly error

--- 
same #398

change the PR target branch because my branch is ruined

2022-12-20 07:36 UTC, kdy1 requested changes
Can you investigate the CI failure?

2022-12-20 07:50 UTC, sunrabbit123 commented
I investigate Extra_error and panic added

2022-12-20 07:51 UTC, sunrabbit123 reviewed
For now, we've finished the investigation here.

2022-12-20 07:51 UTC, sunrabbit123 commented on crates/stc_ts_type_checker/tests/conformance/types/mapped/recursiveMappedTypes.ts.stats.rust-debug
> +    panic: 1,
It's Overflow of Recursive Values Issue

I think that We will should has solution about put dejavu in normalize
There may be other ways than this.

https://github.com/dudykr/stc/blob/36454c34724a476623376e771e9a7703697af328/crates/stc_ts_file_analyzer/src/analyzer/types/mod.rs#L526-L533

2022-12-20 09:52 UTC, sunrabbit123 reviewed
Where is the narrow due to the if?

2022-12-20 09:52 UTC, sunrabbit123 commented on crates/stc_ts_type_checker/tests/conformance/types/intersection/intersectionOfUnionNarrowing.ts.stats.rust-debug
> +    extra_error: 1,
`else narrowing` is incorrect

```ts
declare const a : ((undefined | {
    bProp: string;
}) & ( object)); // { bProp: string; } & object
declare const b : ((undefined | {
    bProp: string;
}) & ( undefined | object)); // ({ bProp: string;} & object) | undefined
```
It should be evaluated as A, but it is evaluated as B

2022-12-20 09:52 UTC, sunrabbit123 commented on crates/stc_ts_type_checker/tests/conformance/controlFlow/controlFlowIfStatement.ts.stats.rust-debug
> +    extra_error: 1,
this too,
wrong narrowing

2022-12-20 09:54 UTC, kdy1 commented
@sunrabbit123 It depends on the kind of narrowing, but you can search for `fn narrow_` using IDE

2022-12-20 09:57 UTC, sunrabbit123 commented
I don't know which narrowing to use.

I found narrow
1. narrow_with_predicate
2. narrow_with_equality

I didn't see anything else.

Also, I didn't find any syntax for putting type in else.

2022-12-20 09:59 UTC, kdy1 commented
<img width="333" alt="image" src="https://user-images.githubusercontent.com/29931815/208639286-19ce09ac-3805-4d1f-bd48-58e8b1317e0e.png">

For `false` parts, please refer to usage sides of those functions

2022-12-21 08:59 UTC, sunrabbit123 commented on crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeRelationships.ts.stats.rust-debug
> -    panic: 0,
`IndexedAccessType` cause overflow,
if you want decrase panic, you should overflow narrow any

2022-12-21 08:59 UTC, sunrabbit123 commented on crates/stc_ts_type_checker/tests/conformance/types/mapped/mappedTypeConstraints2.ts.stats.rust-debug
> +    panic: 1,
this too,

2022-12-21 08:59 UTC, sunrabbit123 commented on crates/stc_ts_type_checker/tests/conformance/types/literal/numericStringLiteralTypes.ts.stats.rust-debug
> +    panic: 1,
this too

2022-12-21 09:00 UTC, sunrabbit123 commented
thx, Now I'm going to start working on Narrow.

2022-12-21 10:11 UTC, sunrabbit123 reviewed
type is wrong

2022-12-21 10:11 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/types/intersection/ofUnionNarrowing/1.swc-stderr
> +  > (({
X & ({
  |     a: object;
  |     b: undefined;
  | } | {
  |     a: undefined;
  |     b: object;
  | })

2022-12-21 10:11 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/types/intersection/ofUnionNarrowing/1.swc-stderr
> +  > any
string

2022-12-22 06:26 UTC, sunrabbit123 reviewed
why don't apply strictNullCheck Options

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/types/mapped/recursiveMappedTypes/3.swc-stderr
> +  > ("type" | "minimum_count" | "maximum_count" | "collapsable")
this should bacome `never`

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/controlFlow/guard/assertions/9.swc-stderr
> +  > string
can't disappear.

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/exprs/typeAssertion/3.swc-stderr
> +  > (string | number)
can't disappear.ㅍ

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/exprs/typeAssertion/4.swc-stderr
> +  > (string | number)
can't disappear.

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/exprs/typeAssertion/8.swc-stderr
> +  > string
can't disappear.

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/types/intersection/intersectionWithUnionConstraint/1.swc-stderr
> +  > string
can't disappear.

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/types/intersection/intersectionWithUnionConstraint/2.swc-stderr
> +  > string
can't disappear.

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/types/intersection/intersectionWithUnionConstraint/3.swc-stderr
> +  > string
can't disappear.

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/controlFlow/guard/assertions/7.swc-stderr
> +  > (string | number)
can't disappear.

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/controlFlow/guard/assertions/6.swc-stderr
> +  > (string | number)
can't disappear.

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/controlFlow/guard/assertions/5.swc-stderr
> +  > (string | number)
can't disappear.

2022-12-22 06:26 UTC, sunrabbit123 commented on crates/stc_ts_file_analyzer/tests/pass/controlFlow/guard/assertions/4.swc-stderr
> +  > (string | number)
can't disappear.

2023-01-10 03:44 UTC, closed without merging