feat(ts/analyzer): Do not report CannotAccessPrivatePropertyFromOutside if the property is not actually being accessed from the outside
dudykr/stc pull request #470
Opened 2023-01-09 21:44 UTC by Subv

**Description:**

The original code was reporting this error if at least one property member of the class was #private.
Example repro of the problem:

```ts
// @target: esnext
class Class1 {
  #private_value!: number;

  get call_get() {
    return 1;
  }

  set call_set(value: number) {
  }
}

let c1 = new Class1();
c1.call_set = 5;

```

Only report a CannotAccessPrivatePropertyFromOutside when a class property is actually being accessed.

I am currently getting 2 more panics and overflows than what is currently reported in the stats files, namely in these files:

`crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNamesAndMethods.ts`
`crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNamesInGenericClasses.ts`

Even a clean clone seems to fail those panics, I included them in the commit for visibility.

My setup:
2021 MacBook Pro M1 Pro (Aarch64)
Node 18.12.1 installed using nvm
rustc 1.66.0-nightly (e7119a030 2022-09-22)

2023-01-09 21:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dudykr/stc?pullRequest=470) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dudykr/stc?pullRequest=470) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dudykr/stc?pullRequest=470) it.</sub>

2023-01-10 02:03 UTC, kdy1 requested changes
Thank you!

2023-01-10 02:03 UTC, kdy1 commented on crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNamesInGenericClasses.ts.stats.rust-debug
> +    panic: 1,
Can you investigate this?

2023-01-10 02:03 UTC, kdy1 commented on crates/stc_ts_type_checker/tests/conformance/classes/members/privateNames/privateNamesAndMethods.ts.stats.rust-debug
> +    panic: 1,
And this?

2023-01-10 14:49 UTC, Subv commented
This PR seems to be superseded by https://github.com/dudykr/stc/pull/476 which also fixes other things, I would suggest concentrating the efforts on that one.

As for the panics, they're stack overflows and I'm unsure how to debug them. My theory is that it's something related to my particular setup (Aarch64 MacOS) since they happen even with a clean clone, any pointers on how to debug that are appreciated.

2023-01-10 14:52 UTC, kdy1 commented
You need a debugger to debug it, and take a look at check.sh or test.sh. After then you will find some env vars

2023-01-31 10:52 UTC, kdy1 commented
Closing as this is superseded

2023-01-31 10:52 UTC, closed without merging