Don't count unimplemented errors as extra errors in stats
dudykr/stc pull request #544
Opened 2023-01-23 16:38 UTC by Amareis

**Description:**

More clearly distinction between unimplemented yet features and wrong current type checking.

2023-01-23 16:58 UTC, kdy1 commented
I think we should include them in the stat

2023-01-23 16:59 UTC, kdy1 commented
Ah, I saw the changes

2023-01-23 16:59 UTC, Amareis commented
Add custom Debug impl for Stats, to not blow-up changes - unimplemented count is printed out only if there is any.

2023-01-23 17:32 UTC, Amareis commented on crates/stc_ts_type_checker/tests/tsc.rs
> +    stats.unimplemented = unimplemented_count;
I don't really know if it should be handled more structurally - with removing such errors from extra errors vector and handling it differently in debug output below. I can do it, if it's needed.

2023-01-23 22:55 UTC, kdy1 requested changes
I'm sorry, but I think this would interfere development

2023-01-24 00:45 UTC, Amareis commented
Fixed

2023-01-24 00:50 UTC, kdy1 commented
I'm not going to accept this, and not sure what you mean by `fixed`

2023-01-24 00:54 UTC, Amareis commented
Oh, just thinks you sayed about merge conflict. Okay, close it now.

2023-01-24 00:54 UTC, closed without merging