Feat(ts/analyzer): deep typeguard about destructor
dudykr/stc pull request #582
Opened 2023-01-31 10:08 UTC by sunrabbit123

**Description:**
```ts
//@strict: true

type Func = <T extends ["a", number] | ["b", string]>(...args: T) => void;

const f60: Func = (kind, payload) => {
  if (kind === "a") {
    payload.toFixed(); // error
  }
  if (kind === "b") {
    payload.toUpperCase(); // error
  }
};
```

2023-01-31 10:48 UTC, kdy1 requested changes
Thank you!

2023-01-31 10:48 UTC, kdy1 commented on crates/stc_ts_file_analyzer/src/analyzer/expr/function.rs
> +                match (*param.ty).normalize() {
```suggestion
                match param.ty.normalize() {
```

2023-01-31 10:48 UTC, kdy1 commented on crates/stc_ts_file_analyzer/src/analyzer/expr/function.rs
> +                        if let Type::Union(Union { types, .. }) = ty.normalize_mut() {
Please use `if let Some(Union { types, .. }) = ty.as_union_type_mut()` instead

2023-01-31 10:48 UTC, kdy1 commented on crates/stc_ts_file_analyzer/src/analyzer/expr/function.rs
> +                                if let Type::Tuple(Tuple { elems, .. }) = ty.normalize_mut() {
Please use if let Some(Tuple { elems, .. }) = ty.as_union_type_mut() instead

2023-02-01 03:35 UTC, sunrabbit123 commented
fixed it

2023-02-01 04:22 UTC, kdy1 submitted a review, later dismissed
Thanks!

2023-02-01 04:25 UTC, kdy1 approved these changes

2023-02-01 04:40 UTC, merged