Following #792, I added type inference.
dudykr/stc pull request #806
Opened 2023-03-08 15:08 UTC by blacktoast

**Description:**
 In #792, there was no type inference for the case `function f11([x=0, y] = []) {}`, so I added it.

**BREAKING CHANGE:**

**Related issue (if exists):**

2023-03-09 02:59 UTC, kdy1 requested changes

2023-03-09 02:59 UTC, kdy1 commented on crates/stc_ts_file_analyzer/tests/pass/es6/destructuring/destructuringWithLiteralInitializers/2.ts
> +f00([1, 'a']);
Please revert this file and create a new test instead

2023-03-09 13:35 UTC, kdy1 requested changes

2023-03-09 13:35 UTC, kdy1 commented on crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs
> +                                                    let mut has_undefined = false;
```rust
let has_undefined = union_obj.contains_undefined()
```
will be enough

2023-03-09 13:35 UTC, kdy1 commented on crates/stc_ts_file_analyzer/src/analyzer/scope/vars.rs
> +                                            ty.elems.push(left_elems_tmp.remove(start));
This is extremely inefficient. Please use `extend` with proper range instead.

2023-03-11 07:21 UTC, kdy1 requested changes
Can you rebase/merge?

2023-03-11 07:37 UTC, kdy1 commented
Note: You may need to wait for https://github.com/dudykr/stc/pull/809

2023-03-11 15:49 UTC, blacktoast commented
Okay, I've rebased it now

2023-03-11 23:32 UTC, kdy1 approved these changes
Thanks!

2023-03-11 23:33 UTC, merged